version: '3'
services:
  db:
    image: mysql:5.6
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    command: bundle exec rails server -b 0.0.0.0
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USER: root
      DATABASE_PASSWORD: password

volumes:
  db_data:
